services:
  - type: web
    name: phishguard-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MODEL_PATH
        value: ./phishing_model
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-super-secret
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
  
  - type: web
    name: phishguard-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html