services:
  - type: web
    name: phishguard-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: MODEL_PATH
        value: ./phishing_model_xgboost.pkl
      - key: FLASK_ENV
        value: production